# Упражнения на методы numpy

In [163]:
import numpy as np

In [164]:
#Создайте нулевой вектор размера 10;
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [165]:
#Как найти размер памяти занимаемый вектором?
np.zeros(10).itemsize

8

In [166]:
# Как создать вектор размера 10, пятый элемент которого = 1?
#не до конца понял вопрос, можно реализовать разными способами 
np.array([0., 0., 0., 0., 1, 0., 0., 0., 0., 0.]), np.ones((1, 10), dtype=int)
# и т д

(array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))

In [167]:
# Как инвертировать вектор (первый элемент становится последним)?
np.flip(np.arange(1,5))

array([4, 3, 2, 1])

In [168]:
# Создайте матрицу 3x3 со значениями от 0 до 8.
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [169]:
# Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения
np.arange(100).reshape(10,10)
#не стал использовать np.random.randint()                                               лень :)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [170]:
# Создайте двумерный-массив с 1(единицами) на границе и 0(нулями) внутри.
a = np.ones((3,3))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

In [171]:
# Как добавить границу (заполненную нулями) вокруг существующего массива (например: массив 5 на 5 из единиц окружить нулями, чтобы он
# превратился в массив 7 на 7?
b = np.zeros((5,5))
np.pad(b, 
       pad_width= 1, 
       constant_values= 1)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [172]:
# Умножьте матрицу 5x3 на матрицу 3x2 (матричное произведение). 

a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)

np.dot(a, b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [173]:
# Вычтите среднее значение каждой строки матрицы. Пояснение к заданию: необходимо вычислить среднее значение каждой строки матрицы и
# вычесть его из элементов соответствующей строки.

ar = np.arange(9).reshape(3,3)

for i in range(len(ar)):
    mean = ar[i].mean()
    for j in range(len(ar)):
        ar[i][j] = ar[i][j] - mean
        
ar

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

# Упражнения на методы pandas

1. Напишите программу для подсчета количества столбцов в DataFrame.
2. Напишите программу для преобразования заданного списка списков (как пример: [[2, 4], [1, 3]]) в Dataframe.
3. Напишите программу, чтобы проверить, присутствует ли данный столбец в DataFrame или нет.
4. Напишите программу для объединения двух Series в DataFrame.
5. Напишите программу для удаления списка строк из указанного DataFrame.
6. Напишите программу для подсчета значений NaN в одном или нескольких столбцах в DataFrame.
7. Напишите программу для добавления одной строки в существующий DataFrame.

In [174]:
import pandas as pd

1 зад

In [175]:
grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90],
 'Sam': [94, 77, 90], 'Katie': [100, 81, 82],
 'Bob': [83, 65, 85]}
df = pd.DataFrame(grades_dict)

In [176]:
df.head()

   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [177]:
#или
df.shape[0]

3

In [178]:
#или 
len(df)

3

2 зад

In [179]:
pd.DataFrame([[2, 4], [1, 3]])

   0  1
0  2  4
1  1  3

3 zad

In [180]:
df.loc[:, 'Bob'] #не до конца понял суть задания  (?)

0    83
1    65
2    85
Name: Bob, dtype: int64

4 зад

In [181]:
s1 = pd.Series(['f', 'u', 'k'])
s2 = pd.Series(98.6, range(3))

dd = pd.concat([s1, s2], axis=1)
dd.columns = ['fa', 'pepe']

dd

  fa  pepe
0  f  98.6
1  u  98.6
2  k  98.6

5 zad

In [182]:
dd.drop('fa', axis=1)

   pepe
0  98.6
1  98.6
2  98.6

6 zad

In [183]:
df1 = df.copy()
df1

   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [184]:
df1 = df1[df1 < 80]
df1

   Wally  Eva   Sam  Katie   Bob
0    NaN  NaN   NaN    NaN   NaN
1    NaN  NaN  77.0    NaN  65.0
2   70.0  NaN   NaN    NaN   NaN

In [185]:
df1.isna().sum()

Wally    2
Eva      3
Sam      2
Katie    3
Bob      2
dtype: int64

7 zad

In [186]:
df

   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85

In [187]:
new = pd.DataFrame([9,9,9],columns=['Anna'])

In [ ]:
pd.concat([df, new]) #на быструю руку но  смысл понятен

   Wally    Eva   Sam  Katie   Bob  Anna
0   87.0  100.0  94.0  100.0  83.0   NaN
1   96.0   87.0  77.0   81.0  65.0   NaN
2   70.0   90.0  90.0   82.0  85.0   NaN
0    NaN    NaN   NaN    NaN   NaN   9.0
1    NaN    NaN   NaN    NaN   NaN   9.0
2    NaN    NaN   NaN    NaN   NaN   9.0